"""
Download and filter code data from The Stack v2 for Atlas training.

Target languages: TypeScript/TSX, Go, Rust, Shell/Bash
Also includes: Dockerfile, YAML, TOML, JSON configs

Usage:
    python scripts/download_data.py --output data/raw/ --max-size-gb 20
"""

import argparse
import json
from pathlib import Path

from datasets import load_dataset
from tqdm import tqdm


# The Stack v2 language mappings
LANGUAGE_MAP = {
    "typescript": "TypeScript",
    "tsx": "TSX",
    "go": "Go",
    "rust": "Rust",
    "shell": "Shell",
    "bash": "Shell",
    "dockerfile": "Dockerfile",
    "yaml": "YAML",
    "toml": "TOML",
    "json": "JSON",
}

# File extensions to include
EXTENSIONS = {
    ".ts", ".tsx", ".jsx",
    ".go",
    ".rs",
    ".sh", ".bash", ".zsh",
    "Dockerfile", ".dockerfile",
    ".yaml", ".yml",
    ".toml",
    ".json",
    ".nginx", ".conf",
}

# Quality filters
MIN_LINES = 5
MAX_LINES = 5000
MIN_CHARS = 50
MAX_CHARS = 100000
MAX_LINE_LENGTH = 500  # Reject files with very long lines (likely minified)
MAX_COMMENT_RATIO = 0.7  # Reject files that are mostly comments


def is_likely_autogenerated(content: str) -> bool:
    """Detect auto-generated files."""
    markers = [
        "auto-generated", "autogenerated", "do not edit",
        "generated by", "this file is generated",
        "code generated", "machine generated",
    ]
    first_lines = content[:500].lower()
    return any(marker in first_lines for marker in markers)


def is_minified(content: str) -> bool:
    """Detect minified files."""
    lines = content.split("\n")
    if not lines:
        return False
    avg_line_length = sum(len(l) for l in lines) / len(lines)
    return avg_line_length > MAX_LINE_LENGTH


def passes_quality_filter(content: str) -> bool:
    """Apply quality filters to code content."""
    lines = content.split("\n")
    num_lines = len(lines)

    if num_lines < MIN_LINES or num_lines > MAX_LINES:
        return False
    if len(content) < MIN_CHARS or len(content) > MAX_CHARS:
        return False
    if is_likely_autogenerated(content):
        return False
    if is_minified(content):
        return False

    return True


def has_secrets(content: str) -> bool:
    """Basic check for leaked secrets/keys."""
    import re
    patterns = [
        r'(?:api[_-]?key|apikey)\s*[=:]\s*["\'][a-zA-Z0-9]{20,}',
        r'(?:secret|password|passwd|pwd)\s*[=:]\s*["\'][^\s]{8,}',
        r'AKIA[0-9A-Z]{16}',  # AWS access key
        r'ghp_[a-zA-Z0-9]{36}',  # GitHub token
        r'sk-[a-zA-Z0-9]{32,}',  # OpenAI-style key
    ]
    for pattern in patterns:
        if re.search(pattern, content, re.IGNORECASE):
            return True
    return False


def download_and_filter(output_dir: str, max_size_gb: float = 20):
    """Download from The Stack v2, filter, and save as JSONL."""
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    total_bytes = 0
    max_bytes = max_size_gb * 1024 ** 3
    stats = {"total_seen": 0, "passed": 0, "rejected": {}}

    for lang_key, lang_name in LANGUAGE_MAP.items():
        print(f"\nDownloading {lang_name}...")
        output_file = output_path / f"{lang_key}.jsonl"

        try:
            # The Stack v2 — streaming to avoid downloading everything at once
            ds = load_dataset(
                "bigcode/the-stack-v2-dedup",
                data_dir=f"data/{lang_name}",
                split="train",
                streaming=True,
            )
        except Exception as e:
            print(f"  Skipping {lang_name}: {e}")
            continue

        count = 0
        with open(output_file, "w") as f:
            for sample in tqdm(ds, desc=f"  Filtering {lang_name}"):
                stats["total_seen"] += 1
                content = sample.get("content", "")

                if not passes_quality_filter(content):
                    stats["rejected"]["quality"] = stats["rejected"].get("quality", 0) + 1
                    continue

                if has_secrets(content):
                    stats["rejected"]["secrets"] = stats["rejected"].get("secrets", 0) + 1
                    continue

                # Passed all filters
                record = {
                    "text": content,
                    "language": lang_key,
                    "size": len(content),
                }
                line = json.dumps(record) + "\n"
                f.write(line)
                total_bytes += len(line.encode())
                count += 1
                stats["passed"] += 1

                if total_bytes >= max_bytes:
                    print(f"\nReached {max_size_gb}GB limit. Stopping.")
                    break

            print(f"  Saved {count:,} files for {lang_name}")

        if total_bytes >= max_bytes:
            break

    # Save stats
    with open(output_path / "stats.json", "w") as f:
        json.dump(stats, f, indent=2)
    print(f"\nDone. Total: {stats['passed']:,} files passed / {stats['total_seen']:,} seen")
    print(f"Size: {total_bytes / 1024**3:.2f} GB")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Download and filter code data for Atlas")
    parser.add_argument("--output", default="data/raw/", help="Output directory")
    parser.add_argument("--max-size-gb", type=float, default=20, help="Max total data size in GB")
    args = parser.parse_args()
    download_and_filter(args.output, args.max_size_gb)
